export const INIT_REQUESTED = "INIT_REQUESTED";
export const INIT_SUCCESS = "INIT_SUCCESS";
export const INIT_FAILED = "INIT_FAILED";

export const SET_STATUS_SUCCESS = "SET_STATUS_SUCCESS";
export const SET_STATUS_FAILED = "SET_STATUS_FAILED";
export const SET_STATUS_CLEAR = "SET_STATUS_CLEAR";

export const CREATE_FILE_REQUESTED = "CREATE_FILE_REQUESTED";
export const CREATE_FILE_SUCCESS = "CREATE_FILE_SUCCESS";
export const CREATE_FILE_FAILED = "CREATE_FILE_FAILED";

export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILED = "UPLOAD_FILE_FAILED";
