export const SET_STATUS_SUCCESS = "SET_STATUS_SUCCESS";
export const SET_STATUS_FAILED = "SET_STATUS_FAILED";
export const SET_STATUS_CLEAR = "SET_STATUS_CLEAR";

export const GET_FIRST_REQUESTED = "GET_FIRST_REQUESTED";
export const GET_FIRST_SUCCESS = "GET_FIRST_SUCCESS";
export const GET_FIRST_FAILED = "GET_FIRST_FAILED";

export const GET_SECOND_SUCCESS = "GET_SECOND_SUCCESS";
export const GET_SECOND_FAILED = "GET_SECOND_FAILED";
